"""empty message

Revision ID: 1d8ece221846
Revises: 
Create Date: 2021-05-09 22:30:18.599833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8ece221846'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commun_name', sa.String(length=100), nullable=False),
    sa.Column('api_cientific_name', sa.String(length=100), nullable=False),
    sa.Column('local_cientific_name', sa.String(length=100), nullable=False),
    sa.Column('plant_image', sa.String(length=2000), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('general', sa.String(length=500), nullable=False),
    sa.Column('utilization', sa.String(length=150), nullable=False),
    sa.Column('seeding', sa.String(length=500), nullable=False),
    sa.Column('caring', sa.String(length=500), nullable=False),
    sa.Column('light', sa.String(length=50), nullable=False),
    sa.Column('deep', sa.String(length=50), nullable=False),
    sa.Column('distancebetween', sa.String(length=50), nullable=False),
    sa.Column('germination', sa.String(length=50), nullable=False),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('harving', sa.String(length=50), nullable=False),
    sa.Column('num_water_freq', sa.Integer(), nullable=True),
    sa.Column('water_freq', sa.String(length=50), nullable=True),
    sa.Column('last_water', sa.Date(), nullable=True),
    sa.Column('num_fertilizer_freq', sa.Integer(), nullable=True),
    sa.Column('fertilizer_freq', sa.String(length=50), nullable=True),
    sa.Column('last_fertilizer', sa.Date(), nullable=True),
    sa.Column('num_prunning_freq', sa.Integer(), nullable=True),
    sa.Column('prunning_freq', sa.String(length=50), nullable=True),
    sa.Column('last_prunning', sa.Date(), nullable=True),
    sa.Column('num_pesticide_freq', sa.Integer(), nullable=True),
    sa.Column('pesticide_freq', sa.String(length=50), nullable=True),
    sa.Column('last_pesticide', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commun_name'),
    sa.UniqueConstraint('commun_name'),
    sa.UniqueConstraint('local_cientific_name'),
    sa.UniqueConstraint('local_cientific_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('first_surname', sa.String(length=100), nullable=True),
    sa.Column('second_surname', sa.String(length=100), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('user_image', sa.String(length=2000), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('photo1', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['user.user_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('user_image', sa.String(length=2000), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('personal_description', sa.String(length=100), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('hobbies', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['user.user_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tasks', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todolist')
    op.drop_table('profile')
    op.drop_table('garden')
    op.drop_table('favorites')
    op.drop_table('user')
    op.drop_table('plant')
    # ### end Alembic commands ###
